export declare const attrsGroups: {
    animationAddition: string[];
    animationAttributeTarget: string[];
    animationEvent: string[];
    animationTiming: string[];
    animationValue: string[];
    conditionalProcessing: string[];
    core: string[];
    graphicalEvent: string[];
    presentation: string[];
    xlink: string[];
    documentEvent: string[];
    filterPrimitive: string[];
    transferFunction: string[];
};
export declare const attrsGroupsDefaults: {
    core: {
        "xml:space": string;
    };
    filterPrimitive: {
        x: string;
        y: string;
        width: string;
        height: string;
    };
    presentation: {
        clip: string;
        "clip-path": string;
        "clip-rule": string;
        mask: string;
        opacity: string;
        "solid-color": string;
        "solid-opacity": string;
        "stop-color": string;
        "stop-opacity": string;
        "fill-opacity": string;
        "fill-rule": string;
        fill: string;
        stroke: string;
        "stroke-width": string;
        "stroke-linecap": string;
        "stroke-linejoin": string;
        "stroke-miterlimit": string;
        "stroke-dasharray": string;
        "stroke-dashoffset": string;
        "stroke-opacity": string;
        "paint-order": string;
        "vector-effect": string;
        "viewport-fill": string;
        "viewport-fill-opacity": string;
        display: string;
        visibility: string;
        "marker-start": string;
        "marker-mid": string;
        "marker-end": string;
        "color-interpolation": string;
        "color-interpolation-filters": string;
        "color-rendering": string;
        "shape-rendering": string;
        "text-rendering": string;
        "image-rendering": string;
        "buffered-rendering": string;
        "font-style": string;
        "font-variant": string;
        "font-weight": string;
        "font-stretch": string;
        "font-size": string;
        "font-size-adjust": string;
        kerning: string;
        "letter-spacing": string;
        "word-spacing": string;
        "text-decoration": string;
        "text-anchor": string;
        "text-overflow": string;
        "writing-mode": string;
        "glyph-orientation-vertical": string;
        "glyph-orientation-horizontal": string;
        direction: string;
        "unicode-bidi": string;
        "dominant-baseline": string;
        "alignment-baseline": string;
        "baseline-shift": string;
    };
    transferFunction: {
        slope: string;
        intercept: string;
        amplitude: string;
        exponent: string;
        offset: string;
    };
};
export declare const inheritableAttrs: string[];
export declare const colorsProps: string[];
export declare const referencesProps: string[];
